from __future__ import annotations

"""
Define el catalogo editable de palabras y frases usadas por el subcriterio de keywords del cuerpo.
"""

PHISHING_KEYWORDS = {
    "urgency": {
        "es": [
            "urgente",
            "accion requerida",
            "requiere su atencion inmediata",
            "de forma inmediata",
            "en las proximas 24 horas",
            "ultimo aviso",
            "plazo limite",
            "respuesta inmediata",
            "tiempo limitado",
            "requiere respuesta inmediata",
        ],
        "en": [
            "urgent",
            "immediate action required",
            "action required",
            "within 24 hours",
            "final notice",
            "time-sensitive",
            "respond immediately",
            "limited time",
            "requires immediate attention",
        ],
        "fr": [
            "urgent",
            "action requise",
            "immediatement",
            "dans les 24 heures",
            "dernier avertissement",
            "reponse immediate",
        ],
        "de": [
            "dringend",
            "sofortige aktion erforderlich",
            "innerhalb von 24 stunden",
            "letzte warnung",
            "umgehend antworten",
        ],
        "it": [
            "urgente",
            "azione richiesta",
            "immediatamente",
            "entro 24 ore",
            "ultimo avviso",
        ],
        "pt": [
            "urgente",
            "acao necessaria",
            "imediatamente",
            "dentro de 24 horas",
            "ultimo aviso",
        ],
    },
    "threat_fear": {
        "es": [
            "cuenta bloqueada",
            "acceso restringido",
            "actividad sospechosa",
            "intento de acceso no autorizado",
            "riesgo de seguridad",
            "violacion de seguridad",
            "bloqueo permanente",
        ],
        "en": [
            "account blocked",
            "suspicious activity",
            "unauthorized access",
            "security breach",
            "risk detected",
            "permanent suspension",
        ],
        "fr": [
            "compte bloque",
            "activite suspecte",
            "acces non autorise",
            "violation de securite",
        ],
        "de": [
            "konto gesperrt",
            "verdachtige aktivitet",
            "unbefugter zugriff",
            "sicherheitsverstoss",
        ],
        "it": [
            "account bloccato",
            "attivita sospetta",
            "accesso non autorizzato",
            "violazione di sicurezza",
        ],
        "pt": [
            "conta bloqueada",
            "atividade suspeita",
            "acesso nao autorizado",
            "violacao de seguranca",
        ],
    },
    "authority_impersonation": {
        "es": [
            "departamento de seguridad",
            "soporte tecnico",
            "equipo de it",
            "administracion",
            "direccion financiera",
            "recursos humanos",
            "auditoria interna",
        ],
        "en": [
            "security department",
            "it support",
            "technical support",
            "finance department",
            "human resources",
            "internal audit",
        ],
        "fr": [
            "service de securite",
            "support technique",
            "service informatique",
            "direction financiere",
        ],
        "de": [
            "sicherheitsabteilung",
            "it-support",
            "finanzabteilung",
            "personalabteilung",
        ],
        "it": [
            "reparto sicurezza",
            "supporto tecnico",
            "ufficio it",
            "ufficio finanziario",
        ],
        "pt": [
            "departamento de seguranca",
            "suporte tecnico",
            "equipe de ti",
            "departamento financeiro",
        ],
    },
    "credential_request": {
        "es": [
            "verifique su cuenta",
            "confirme sus datos",
            "actualice su informacion",
            "validar identidad",
            "introduzca sus credenciales",
            "restablecer contrasena",
        ],
        "en": [
            "verify your account",
            "confirm your information",
            "update your details",
            "validate your identity",
            "enter your credentials",
            "reset your password",
        ],
        "fr": [
            "verifiez votre compte",
            "confirmez vos informations",
            "mettre a jour vos donnees",
            "reinitialiser le mot de passe",
        ],
        "de": [
            "konto verifizieren",
            "daten bestatigen",
            "informationen aktualisieren",
            "passwort zurucksetzen",
        ],
        "it": [
            "verifica il tuo account",
            "conferma i tuoi dati",
            "aggiorna le informazioni",
            "reimposta la password",
        ],
        "pt": [
            "verifique sua conta",
            "confirme seus dados",
            "atualize suas informacoes",
            "redefinir senha",
        ],
    },
    "call_to_action": {
        "es": [
            "haga clic aqui",
            "acceda aqui",
            "revise el enlace",
            "descargar documento",
            "ver factura",
            "abrir archivo adjunto",
            "retirar ahora",
            "retire ahora",
            "reclamar ahora",
            "acceder a la cartera",
        ],
        "en": [
            "click here",
            "access here",
            "review the link",
            "download document",
            "view invoice",
            "open attachment",
            "withdraw now",
            "claim now",
            "connect wallet",
            "access wallet",
            "review transaction",
        ],
        "fr": [
            "cliquez ici",
            "acceder ici",
            "telecharger le document",
            "voir la facture",
        ],
        "de": [
            "hier klicken",
            "jetzt zugreifen",
            "dokument herunterladen",
            "rechnung ansehen",
        ],
        "it": [
            "clicca qui",
            "accedi qui",
            "scarica il documento",
            "visualizza fattura",
        ],
        "pt": [
            "clique aqui",
            "acesse aqui",
            "baixar documento",
            "ver fatura",
        ],
    },
    "incentive_reward": {
        "es": [
            "premio",
            "recompensa",
            "beneficio",
            "reembolso",
            "bonificacion",
            "ha sido seleccionado",
            "cliente elegible",
            "fondos disponibles",
        ],
        "en": [
            "reward",
            "prize",
            "bonus",
            "refund",
            "you have been selected",
            "eligible client",
            "available funds",
            "eligible account",
        ],
        "fr": [
            "recompense",
            "prix",
            "bonus",
            "remboursement",
        ],
        "de": [
            "belohnung",
            "preis",
            "bonus",
            "ruckerstattung",
        ],
        "it": [
            "premio",
            "ricompensa",
            "bonus",
            "rimborso",
        ],
        "pt": [
            "premio",
            "recompensa",
            "bonus",
            "reembolso",
        ],
    },
    "phishing_corporate_context": {
        "es": [
            "revision pendiente",
            "documentacion adjunta",
            "proceso interno",
            "aprobacion requerida",
            "segun lo comentado",
            "como acordamos",
        ],
        "en": [
            "pending review",
            "attached documentation",
            "internal process",
            "approval required",
            "as discussed",
            "as agreed",
        ],
        "fr": [
            "revision en attente",
            "documentation jointe",
            "processus interne",
            "comme convenu",
        ],
        "de": [
            "ausstehende prufung",
            "interner prozess",
            "wie besprochen",
        ],
        "it": [
            "revisione in sospeso",
            "documentazione allegata",
            "come concordato",
        ],
        "pt": [
            "revisao pendente",
            "documentacao anexada",
            "como combinado",
        ],
    },
    "financial_transaction": {
        "es": [
            "retiro",
            "retirada",
            "retirar fondos",
            "transferencia pendiente",
            "transaccion pendiente",
            "saldo disponible",
            "cuenta financiera",
            "proceso de retiro",
            "liberacion de fondos",
            "solicitud de retiro",
            "historial de transacciones",
        ],
        "en": [
            "withdrawal",
            "withdrawals",
            "withdraw process",
            "withdraw funds",
            "pending transfer",
            "pending transaction",
            "available balance",
            "transaction history",
            "fund release",
            "funds available",
            "withdrawal request",
            "asset recovery",
            "payment release",
        ],
        "fr": [
            "retrait",
            "transfert en attente",
            "transaction en attente",
            "solde disponible",
        ],
        "de": [
            "auszahlung",
            "uberweisung ausstehend",
            "transaktion ausstehend",
            "verfugbares guthaben",
        ],
        "it": [
            "prelievo",
            "trasferimento in sospeso",
            "transazione in sospeso",
            "saldo disponibile",
        ],
        "pt": [
            "saque",
            "retirada",
            "transferencia pendente",
            "transacao pendente",
            "saldo disponivel",
        ],
    },
    "crypto_assets": {
        "es": [
            "activos digitales",
            "billetera",
            "wallet",
            "criptoactivos",
            "cartera digital",
            "criptomonedas",
            "token",
            "red blockchain",
        ],
        "en": [
            "digital assets",
            "wallet account",
            "external wallet",
            "crypto wallet",
            "digital wallet",
            "erc-20 wallet",
            "erc 20 wallet",
            "erc-20",
            "erc 20",
            "crypto assets",
            "cryptocurrency",
            "token balance",
            "blockchain network",
        ],
        "fr": [
            "actifs numeriques",
            "portefeuille",
            "wallet",
        ],
        "de": [
            "digitale vermogenswerte",
            "wallet",
            "krypto assets",
        ],
        "it": [
            "asset digitali",
            "wallet",
            "portafoglio",
        ],
        "pt": [
            "ativos digitais",
            "wallet",
            "carteira",
        ],
    },
    "account_access": {
        "es": [
            "inicie sesion",
            "iniciar sesion",
            "acceder a su cuenta",
            "panel de control",
            "portal del cliente",
        ],
        "en": [
            "log in",
            "login",
            "sign in",
            "access your account",
            "dashboard",
            "customer portal",
        ],
        "fr": [
            "connexion",
            "se connecter",
            "acceder au compte",
        ],
        "de": [
            "anmelden",
            "kontozugang",
            "dashboard",
        ],
        "it": [
            "accedi",
            "accesso all account",
            "dashboard",
        ],
        "pt": [
            "iniciar sessao",
            "acessar sua conta",
            "painel",
        ],
    },
}
